### ISSUE TITLE
neural_net

### ISSUE THREAD

**Issue by rajeshrocknroll** [rthadur/recaptcha#229]
sdfdssdfdssdsdfsdfsdfsdfdsfsdfsdfsdfsdfsdfdsfsdfsdfsdfdsfsdfsdfsdfsdfsdfdsf load_dynamic return _load(spec)
CUDA/cuDNN version: 434

**Comment by ymodak** [comment]
```
From the template it looks like you are installing **TF-GPU** pre-built binaries.  
TensorFlow Version >= 1.13 requires CUDA 10.0 and Tensorflow Version < 1.13  
 (till TensorFLow 1.5) requires CUDA 9.0.  

* If have above configuration and using ”Windows” platform -  
     *Try adding the CUDA, CUPTI, and cuDNN installation directories  
       to the %PATH% environment variable. 
     *Take a look at the windows setup guide to know more.
* If have above configuration and using ”Ubuntu/Linux” platform -  
     *Try adding the CUDA, CUPTI, and cuDNN installation directories to the  
       $LD_LIBRARY_PATH environment variable. 
     *Take a look at the linux setup guide to know more.
```

**Comment by ymodak** [comment]
From the template it looks like you are installing **TensorFlow** (TF) prebuilt binaries.

**TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets.**
Therefore on any CPU that do not have these instruction sets either CPU or GPU version of TF will fail to load.

 Apparently your CPU model does not support AVX instruction sets. 
You can still use TensorFlow with the alternatives given below:
* Try Google Colab to use TensorFlow.
    * The easiest way to use TF will be to switch to google colab. You get pre-installed latest stable TF version. Also you can use ```pip install``` to install any other preferred TF version.
    * It has an added advantage since you can you easily switch to different hardware accelerators (cpu, gpu, tpu) as per the task. 
    * All you need is a good internet connection and you are all set.
* Try to build TF from sources by changing CPU optimization flags.

**Comment by ymodak** [comment]
From the stack trace it looks like you are hitting windows path length limit.
* Try to disable path length limit on Windows 10.
  * Refer [disable path length limit instructions guide](https://mspoweruser.com/ntfs-260-character-windows-10/).

**Comment by ymodak** [comment]
**1. Installing **TensorFlow-GPU** (TF) prebuilt binaries**

*TF Version >= 1.13 requires CUDA 10.0 and TF Version < 1.13 (till TF 1.5) requires CUDA 9.0.* 
* If you have above configuration and using _**Windows**_ platform -  
     * Try adding the CUDA, CUPTI, and cuDNN installation directories to the %PATH% environment 
        variable. 
     * Refer [windows setup guide](https://www.tensorflow.org/install/gpu#windows_setup).
* If you have above configuration and using _**Ubuntu/Linux**_ platform -  
     * Try adding the CUDA, CUPTI, and cuDNN installation directories to the $LD_LIBRARY_PATH 
       environment variable. 
     * Refer [linux setup guide](https://www.tensorflow.org/install/gpu#linux_setup).

*If error still persists or not installing TF-GPU then proceed to step 2.*

-----------------------------------------------------------------------------------------------

**2. Installing **TensorFlow** (TF) prebuilt binaries**

*TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets.*

Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.
Apparently, your CPU model does not support AVX instruction sets.You can still use TensorFlow with the alternatives given below:
* Try Google Colab to use TensorFlow.
    * The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true). You get pre-installed latest stable TF version. Also you can use ```pip install``` to install any other preferred TF version.
    * It has an added advantage since you can you easily switch to different hardware accelerators     
      (cpu, gpu, tpu) as per the task. 
    * All you need is a good internet connection and you are all set.
* Try to build TF from sources by changing CPU optimization flags.

Please let us know if this helps.

**Comment by rajeshrocknroll** [comment]
s

**Comment by rajeshrocknroll** [comment]
s

**Comment by rajeshrocknroll** [comment]
s

**Comment by rajeshrocknroll** [comment]
s

**Comment by rajeshrocknroll** [comment]
s

**Comment by rajeshrocknroll** [comment]
s

**Comment by rajeshrocknroll** [comment]
s

**Comment by rajeshrocknroll** [comment]
s

**Comment by rajeshrocknroll** [comment]
s

**Comment by rajeshrocknroll** [comment]
s

**Comment by rajeshrocknroll** [comment]
s

**Comment by rajeshrocknroll** [comment]
s

**Comment by rajeshrocknroll** [comment]
s

**Comment by rajeshrocknroll** [comment]
s

**Comment by rajeshrocknroll** [comment]
s

**Comment by rajeshrocknroll** [comment]
s

**Comment by ymodak** [comment]
```python
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
```
