### ISSUE TITLE
dsd

### ISSUE THREAD

**Issue by rajeshrocknroll** [rthadur/recaptcha#234]
sdfdssdfdssdsdfsdfsdfsdfdsfsdfsdfsdfsdfsdfdsfsdfsdfsdfdsfsdfsdfsdfsdfsdfdsf load_dynamic return _load(spec)

CUDA/cuDNN version:222
GPU model and memory:555

**Comment by rajeshrocknroll** [comment]
s

**Comment by rthadur** [comment]
s

**Comment by rajeshrocknroll** [comment]
s

**Comment by rajeshrocknroll** [comment]
s

**Comment by rajeshrocknroll** [comment]
s
